<?php

namespace ContainerRYodEch;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllercancelReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QO4wEWI.App\Controller\EmployeeController::cancelReservation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QO4wEWI.App\\Controller\\EmployeeController::cancelReservation()'] = ($container->privates['.service_locator.QO4wEWI'] ?? $container->load('get_ServiceLocator_QO4wEWIService'))->withContext('App\\Controller\\EmployeeController::cancelReservation()', $container);
    }
}
