<?php

namespace ContainerRYodEch;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllerreserveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G9GZdsS.App\Controller\EmployeeController::reserve()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G9GZdsS.App\\Controller\\EmployeeController::reserve()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carteRepo' => ['privates', 'App\\Repository\\CarteDuJourRepository', 'getCarteDuJourRepositoryService', true],
            'reservationRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'messRequestRepo' => ['privates', 'App\\Repository\\MessRequestRepository', 'getMessRequestRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'carteRepo' => 'App\\Repository\\CarteDuJourRepository',
            'reservationRepo' => 'App\\Repository\\ReservationRepository',
            'messRequestRepo' => 'App\\Repository\\MessRequestRepository',
            'mailer' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\EmployeeController::reserve()', $container);
    }
}
