<?php

namespace ContainerZukpzk0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChefControllermenuDayService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._nIy_GB.App\Controller\ChefController::menuDay()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._nIy_GB.App\\Controller\\ChefController::menuDay()'] = ($container->privates['.service_locator._nIy_GB'] ?? $container->load('get_ServiceLocator_NIyGBService'))->withContext('App\\Controller\\ChefController::menuDay()', $container);
    }
}
