<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CarteDuJour extends \App\Entity\CarteDuJour implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'available' => [parent::class, 'available', null, 16],
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null, 16],
        "\0".parent::class."\0".'compositionAccompagnements' => [parent::class, 'compositionAccompagnements', null, 16],
        "\0".parent::class."\0".'compositionDesserts' => [parent::class, 'compositionDesserts', null, 16],
        "\0".parent::class."\0".'compositionEntrees' => [parent::class, 'compositionEntrees', null, 16],
        "\0".parent::class."\0".'compositionFormules' => [parent::class, 'compositionFormules', null, 16],
        "\0".parent::class."\0".'compositionLieus' => [parent::class, 'compositionLieus', null, 16],
        "\0".parent::class."\0".'compositionPlats' => [parent::class, 'compositionPlats', null, 16],
        "\0".parent::class."\0".'compositionSalades' => [parent::class, 'compositionSalades', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'locked' => [parent::class, 'locked', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'available' => [parent::class, 'available', null, 16],
        'comment' => [parent::class, 'comment', null, 16],
        'compositionAccompagnements' => [parent::class, 'compositionAccompagnements', null, 16],
        'compositionDesserts' => [parent::class, 'compositionDesserts', null, 16],
        'compositionEntrees' => [parent::class, 'compositionEntrees', null, 16],
        'compositionFormules' => [parent::class, 'compositionFormules', null, 16],
        'compositionLieus' => [parent::class, 'compositionLieus', null, 16],
        'compositionPlats' => [parent::class, 'compositionPlats', null, 16],
        'compositionSalades' => [parent::class, 'compositionSalades', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'locked' => [parent::class, 'locked', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
