<?php

namespace ContainerGmvZeex;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.quwmMpH.App\Controller\EmployeeController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.quwmMpH.App\\Controller\\EmployeeController::dashboard()'] = ($container->privates['.service_locator.quwmMpH'] ?? $container->load('get_ServiceLocator_QuwmMpHService'))->withContext('App\\Controller\\EmployeeController::dashboard()', $container);
    }
}
