<?php

namespace ContainerZYVf9fl;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.quwmMpH.App\Controller\EmployeeController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.quwmMpH.App\\Controller\\EmployeeController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carteRepo' => ['privates', 'App\\Repository\\CarteDuJourRepository', 'getCarteDuJourRepositoryService', true],
            'reservationRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'carteRepo' => 'App\\Repository\\CarteDuJourRepository',
            'reservationRepo' => 'App\\Repository\\ReservationRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\EmployeeController::dashboard()', $container);
    }
}
