<?php

namespace ContainerZOmfRFw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NIyGBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._nIy_GB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._nIy_GB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'carteRepo' => ['privates', 'App\\Repository\\CarteDuJourRepository', 'getCarteDuJourRepositoryService', true],
            'reservationRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'em' => '?',
            'carteRepo' => 'App\\Repository\\CarteDuJourRepository',
            'reservationRepo' => 'App\\Repository\\ReservationRepository',
        ]);
    }
}
