<?php

namespace ContainerZOmfRFw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GlRetfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GlRetf_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GlRetf_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'messRequestRepo' => ['privates', 'App\\Repository\\MessRequestRepository', 'getMessRequestRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'reservationRepo' => 'App\\Repository\\ReservationRepository',
            'messRequestRepo' => 'App\\Repository\\MessRequestRepository',
            'em' => '?',
        ]);
    }
}
