<?php

namespace ContainerZOmfRFw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChefControllermanageMealsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CDTyXuX.App\Controller\ChefController::manageMeals()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CDTyXuX.App\\Controller\\ChefController::manageMeals()'] = ($container->privates['.service_locator.CDTyXuX'] ?? $container->load('get_ServiceLocator_CDTyXuXService'))->withContext('App\\Controller\\ChefController::manageMeals()', $container);
    }
}
