<?php

namespace ContainerZOmfRFw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChefControllerreservationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GlRetf_.App\Controller\ChefController::reservations()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GlRetf_.App\\Controller\\ChefController::reservations()'] = ($container->privates['.service_locator.GlRetf_'] ?? $container->load('get_ServiceLocator_GlRetfService'))->withContext('App\\Controller\\ChefController::reservations()', $container);
    }
}
