<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJs1rFh0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJs1rFh0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJs1rFh0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJs1rFh0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJs1rFh0\App_KernelDevDebugContainer([
    'container.build_hash' => 'Js1rFh0',
    'container.build_id' => '01a898a1',
    'container.build_time' => 1764343279,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJs1rFh0');
