<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZYVf9fl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZYVf9fl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZYVf9fl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZYVf9fl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZYVf9fl\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZYVf9fl',
    'container.build_id' => '58f64f68',
    'container.build_time' => 1764844347,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZYVf9fl');
