<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRYodEch\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRYodEch/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRYodEch.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRYodEch\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRYodEch\App_KernelDevDebugContainer([
    'container.build_hash' => 'RYodEch',
    'container.build_id' => 'b931e55e',
    'container.build_time' => 1764778053,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRYodEch');
