<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController'], [], [['text', '/']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\HomeController::__invoke' => [[], ['_controller' => 'App\\Controller\\HomeController'], [], [['text', '/']], [], [], []],
    'App\Controller\HomeController' => [[], ['_controller' => 'App\\Controller\\HomeController'], [], [['text', '/']], [], [], []],
    'App\Controller\RegistrationController::__invoke' => [[], ['_controller' => 'App\\Controller\\RegistrationController'], [], [['text', '/register']], [], [], []],
    'App\Controller\RegistrationController' => [[], ['_controller' => 'App\\Controller\\RegistrationController'], [], [['text', '/register']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
