<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'security-login' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/security-login.6a667623.js',
            ],
            'css' => [
                '/build/security-login.03d2d64d.css',
            ],
        ],
        'security-register' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/security-register.ef775b2d.js',
            ],
            'css' => [
                '/build/security-register.54de80c0.css',
            ],
        ],
        'app-home' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/app-home.bdb42e01.js',
            ],
            'css' => [
                '/build/app-home.bff16bec.css',
            ],
        ],
        'employee-dashboard' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-dashboard.ed0a0279.js',
            ],
            'css' => [
                '/build/employee-dashboard.86e7f347.css',
            ],
        ],
        'employee-reserve' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-reserve.b2d20b07.js',
            ],
            'css' => [
                '/build/employee-reserve.7869a26e.css',
            ],
        ],
        'employee-reservations' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-reservations.bd49d3b0.js',
            ],
            'css' => [
                '/build/employee-reservations.f45ae0df.css',
            ],
        ],
        'employee-modal' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-modal.2aeffdbd.js',
            ],
            'css' => [
                '/build/employee-modal.24ede97a.css',
            ],
        ],
        'employee-mess' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-mess.1dd91d6b.js',
            ],
            'css' => [
                '/build/employee-mess.c5fdd36d.css',
            ],
        ],
        'chef-agenda' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-agenda.b34c5a9e.js',
            ],
            'css' => [
                '/build/chef-agenda.5c7a9f5d.css',
            ],
        ],
        'chef-menu-day' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-menu-day.66f9cf3a.js',
            ],
            'css' => [
                '/build/chef-menu-day.5a766086.css',
            ],
        ],
        'chef-manage-meals' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-manage-meals.30eaf823.js',
            ],
            'css' => [
                '/build/chef-manage-meals.d8217cb4.css',
            ],
        ],
        'chef-select-items' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-select-items.30684b50.js',
            ],
            'css' => [
                '/build/chef-select-items.f2a24b1d.css',
            ],
        ],
        'chef-entrees' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-entrees.31a9b4ca.js',
            ],
            'css' => [
                '/build/534.c5fdd36d.css',
            ],
        ],
        'chef-plats' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-plats.2b0140fe.js',
            ],
            'css' => [
                '/build/534.c5fdd36d.css',
            ],
        ],
        'chef-accompagnements' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-accompagnements.c914d35b.js',
            ],
            'css' => [
                '/build/534.c5fdd36d.css',
            ],
        ],
        'chef-salades' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-salades.be73bd43.js',
            ],
            'css' => [
                '/build/534.c5fdd36d.css',
            ],
        ],
    ],
],

]];
