<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'security-login' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/security-login.6a667623.js',
            ],
            'css' => [
                '/build/security-login.98f2bcf6.css',
            ],
        ],
        'security-register' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/security-register.ef775b2d.js',
            ],
            'css' => [
                '/build/security-register.40b976b0.css',
            ],
        ],
        'app-home' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/app-home.bdb42e01.js',
            ],
            'css' => [
                '/build/app-home.73b8462b.css',
            ],
        ],
        'employee-dashboard' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-dashboard.ed0a0279.js',
            ],
            'css' => [
                '/build/employee-dashboard.04d0d351.css',
            ],
        ],
        'employee-reserve' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-reserve.c8661bc8.js',
            ],
            'css' => [
                '/build/employee-reserve.e484f803.css',
            ],
        ],
        'employee-reservations' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-reservations.bd49d3b0.js',
            ],
            'css' => [
                '/build/employee-reservations.69cdbb6c.css',
            ],
        ],
        'employee-modal' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-modal.2aeffdbd.js',
            ],
            'css' => [
                '/build/employee-modal.784cffd8.css',
            ],
        ],
        'employee-mess' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-mess.1dd91d6b.js',
            ],
            'css' => [
                '/build/employee-mess.b6200df1.css',
            ],
        ],
        'employee-account' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/employee-account.67342150.js',
            ],
            'css' => [
                '/build/employee-account.28f54124.css',
            ],
        ],
        'chef-agenda' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-agenda.b34c5a9e.js',
            ],
            'css' => [
                '/build/chef-agenda.4b13e630.css',
            ],
        ],
        'chef-menu-day' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-menu-day.66f9cf3a.js',
            ],
            'css' => [
                '/build/chef-menu-day.78d4b62c.css',
            ],
        ],
        'chef-manage-meals' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-manage-meals.30eaf823.js',
            ],
            'css' => [
                '/build/chef-manage-meals.9de5d762.css',
            ],
        ],
        'chef-select-items' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-select-items.30684b50.js',
            ],
            'css' => [
                '/build/chef-select-items.61064e35.css',
            ],
        ],
        'chef-reservations' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-reservations.fe9e5b3e.js',
            ],
            'css' => [
                '/build/chef-reservations.24857f37.css',
            ],
        ],
        'chef-settings' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-settings.29f58148.js',
            ],
            'css' => [
                '/build/chef-settings.c48ef458.css',
            ],
        ],
        'chef-accounts' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/chef-accounts.06e844a1.js',
            ],
            'css' => [
                '/build/chef-accounts.8717655c.css',
            ],
        ],
        'chef-entrees' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-entrees.31a9b4ca.js',
            ],
            'css' => [
                '/build/534.b6200df1.css',
            ],
        ],
        'chef-plats' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-plats.2b0140fe.js',
            ],
            'css' => [
                '/build/534.b6200df1.css',
            ],
        ],
        'chef-accompagnements' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-accompagnements.c914d35b.js',
            ],
            'css' => [
                '/build/534.b6200df1.css',
            ],
        ],
        'chef-salades' => [
            'js' => [
                '/build/runtime.d47beb02.js',
                '/build/336.39c7dcd4.js',
                '/build/chef-salades.be73bd43.js',
            ],
            'css' => [
                '/build/534.b6200df1.css',
            ],
        ],
    ],
],

]];
