<?php

namespace ContainerLLOQg3i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChefControllerdeleteAccountService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nGA2c7R.App\Controller\ChefController::deleteAccount()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nGA2c7R.App\\Controller\\ChefController::deleteAccount()'] = ($container->privates['.service_locator.nGA2c7R'] ?? $container->load('get_ServiceLocator_NGA2c7RService'))->withContext('App\\Controller\\ChefController::deleteAccount()', $container);
    }
}
